# Generated by Django 4.1 on 2022-08-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='active', max_length=250, null=True),
        ),
    ]
