# Generated by Django 4.1 on 2023-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_file',
            name='document_ocr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document_file',
            name='document_path',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
