# Generated by Django 4.1 on 2023-02-17 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_profile_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0002_document_file_document_ocr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='document_file',
            old_name='document_ocr',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='document_file',
            old_name='document_name',
            new_name='docFileType',
        ),
        migrations.RemoveField(
            model_name='document_file',
            name='document_details',
        ),
        migrations.RemoveField(
            model_name='document_file',
            name='document_path',
        ),
        migrations.AddField(
            model_name='document_file',
            name='docInsideText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document_file',
            name='docOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.department'),
        ),
        migrations.AddField(
            model_name='document_file',
            name='documentController',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='document_file',
            name='filePath',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='document_file',
            name='is_archived',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='document_file',
            name='is_public',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='document_file',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='document_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('document_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.document_file')),
                ('document_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.tags')),
            ],
        ),
        migrations.CreateModel(
            name='audit_trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatesText', models.TextField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('document_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.document_file')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document_file',
            name='docType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.document_type'),
        ),
    ]
